### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Mrming1994** [AlvinZhu/mod-synthesize-trainer#1]
hi , I try build this module but have error 
![微信图片_20230224123732](https://user-images.githubusercontent.com/43674158/221093026-57ac02a3-54d7-4a24-beec-0d6d62fa8550.png)

**Comment by AlvinZhu** [comment]
https://github.com/AlvinZhu/azerothcore-wotlk/commit/3b9777f4031bb119ea89ef124547e169afa3ef79
